### ISSUE TITLE
Authenticate not working

### ISSUE THREAD

**Issue by Odianosen25** [vandot/pysoftether#3]
Hello, 

When I run `api.authenticate()` I get the following issues

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/hashlib.py", line 122, in __hash_new
    return _hashlib.new(name, data)
ValueError: unsupported hash type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/softether/api.py", line 129, in authenticate
    hashed_password = hashlib.new('sha')
  File "/usr/lib/python3.5/hashlib.py", line 128, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.5/hashlib.py", line 95, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha

```

**Comment by vandot** [comment]
@Odianosen25 as described in this SO post: https://stackoverflow.com/a/11434078/9880163
This is OpenSSL issue on your machine, what OS are you using?

**Comment by Odianosen25** [comment]
Hello @vandot,

Thanks for the response. I am running it on a raspberry pi, running Raspbian.

Regards

**Comment by vandot** [comment]
@Odianosen25 as described in post in my previous comment it's not issue of pysoftether, its system issue, maybe your are missing `libssl-dev` or some other dev ssl package, depends what ssl implementation Raspbian uses

**Comment by Odianosen25** [comment]
Hello @vandot ,

Thanks for the response again. I have that package installed but digging thru I found out that these are the supported algorithms for [hashlib.new](https://docs.python.org/3/library/hashlib.html#hash-algorithms)
```
BLAKE2b512, BLAKE2s256, MD4, MD5, MD5-SHA1, RIPEMD160, SHA1,
SHA224, SHA256, SHA384, SHA512, blake2b, blake2b512, blake2s,
blake2s256, md4, md5, md5-sha1, ripemd160, sha1, sha224, sha256,
sha384, sha3_224, sha3_256, sha3_384, sha3_512, sha512,
shake_128, shake_256, whirlpool
```` 

Is it possible that instead of [line 129](https://github.com/vandot/pysoftether/blob/master/softether/api.py#L129) be

```
hashed_password = hashlib.new('sha')
``` 
should actually be
```
hashed_password = hashlib.new('sha1')
```
Regards

**Comment by vandot** [comment]
@Odianosen25 
what version of OpenSSL you have, mine is OpenSSL 1.0.2g on Linux and LibreSSL 2.6.5 on MacOS
On both I have inside `hashlib.algorithms_available` available `sha`

**Comment by Odianosen25** [comment]
@vandot,

OpenSSL version is `OpenSSL 1.1.0j  20 Nov 2018`

As for `hashlib`, I get 
```
>>> hashlib.algorithms_available
{'sha256', 'sha224', 'blake2s256', 'md5', 'md5-sha1', 'ripemd160', 'sha384', 'blake2b512', 'sha1', 'sha512', 'md4', 'whirlpool'}
```

Regards

**Comment by Odianosen25** [comment]
Hello @vandot,

Please last question. Will your code ever support the new [official api](https://github.com/SoftEtherVPN/SoftEtherVPN/tree/master/developer_tools/vpnserver-jsonrpc-clients/)?

Kind regards

**Comment by ford1813** [comment]
> Hello @vandot ,
> 
> Thanks for the response again. I have that package installed but digging thru I found out that these are the supported algorithms for [hashlib.new](https://docs.python.org/3/library/hashlib.html#hash-algorithms)
> 
> ```
> BLAKE2b512, BLAKE2s256, MD4, MD5, MD5-SHA1, RIPEMD160, SHA1,
> SHA224, SHA256, SHA384, SHA512, blake2b, blake2b512, blake2s,
> blake2s256, md4, md5, md5-sha1, ripemd160, sha1, sha224, sha256,
> sha384, sha3_224, sha3_256, sha3_384, sha3_512, sha512,
> shake_128, shake_256, whirlpool
> ```
> 
> Is it possible that instead of [line 129](https://github.com/vandot/pysoftether/blob/master/softether/api.py#L129) be
> 
> ```
> hashed_password = hashlib.new('sha')
> ```
> 
> should actually be
> 
> ```
> hashed_password = hashlib.new('sha1')
> ```
> 
> Regards

I set to 'sha1', anyway not work.

**Comment by aweher** [comment]
Same issue here

```>>> hashlib.algorithms_available
{'blake2b', 'sha3_256', 'sha512_224', 'sha512', 'whirlpool', 'md4', 'sha384', 'sha224', 'shake_128', 'shake_256', 'sha1', 'sm3', 'ripemd160', 'sha512_256', 'blake2s', 'sha256', 'md5-sha1', 'sha3_224', 'sha3_384', 'md5', 'sha3_512'

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by triple-it** [comment]
The official API would be nice indeed!

```
import requests
import json
# urllib3
import urllib3
# for debugging
import pdb

SERVER_URL = "https://localhost:5555"
# api url
API_URL = SERVER_URL + "/api/"

def get_server_info(**params):
    payload = {
            "jsonrpc": "2.0",
            "id": "rpc_call_id",
            "method": "GetServerInfo",
            "params": {
                "HubName_str": params.get("hubname", None),
                "Port_u32": params.get("port",None),
                "Enable_bool": params.get("enabled",None)
                }
            }

    headers= {'Content-Type': 'application/json; charset=utf-8',
              'X-VPNADMIN-HUBNAME': '',
              'X-VPNADMIN-PASSWORD': 'password'}
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    response = requests.request("POST", url=API_URL, headers=headers, data = json.dumps(payload), verify = False)
    print(response.text)
    data = response.json()
    return data

get_server_info()
```

**Comment by DGHC** [comment]
Any update on this?  I'm finding the same issue.  My Python 2 server has both 'sha' and 'sha1' available, and they give different answers:

```
> hh = hashlib.new('sha') 
> hh.update('testing'.encode('latin-1')) 
> hh.hexdigest()  
'd793d072b6d24ed501d6c9938691f161129d5de4'  
> hh = hashlib.new('sha1')  
> hh.update('testing'.encode('latin-1'))  
> hh.hexdigest()  
'dc724af18fbdd4e59189f5fe768a5f8311527050'  
```

The key question is, what hash in Python 3 would give the same output as the 'sha' hash in Python 2?  The 'sha1' output is correct, but I don't know what the 'sha' algorithm is doing.

**Comment by DGHC** [comment]
Breakthrough!  I've never felt more like Boris from Goldeneye...

Turns out that `'sha'` is referring to the outdated SHA-0 algorithm.  There's very little on the web about it, other than warnings not to use it as it is not secure.  It is not equivalent to `'sha1'`.

The user 'acerun' has created a Python module for the SHA-0 algorithm here:
https://github.com/acerun/python3-sha0/blob/master/sha0.py

I added that module in my `dist-packages` folder, then added `import sha0` at the top of the SoftEther `api.py` file.  I then replaced all occurences of `hashlib.new('sha')` (in `api.py`) with `sha0.sha0Hash()` and it worked!  

Note that I had to change the shebang at the top of sha0.py to something that was relevant to my environment (Python 3).
